# Generated by Django 6.0.2 on 2026-02-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto real de la botella', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='icono',
            field=models.CharField(blank=True, help_text='Emoji temporal', max_length=10, null=True),
        ),
    ]
