# Generated by Django 6.0.2 on 2026-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_imagen_alter_producto_es_vip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(default=0, help_text='0 es el primero. Usa números mayores para enviarlo al final.'),
        ),
    ]
