# Generated by Django 6.0.2 on 2026-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='pendiente@correo.com', max_length=254),
            preserve_default=False,
        ),
    ]
